### ISSUE TITLE
App Crach when start Calendar on Android 6.0

### ISSUE THREAD

**Issue by Pahanuch** [prolificinteractive/material-calendarview#444]
```
> java.lang.RuntimeException: An error occurred while executing doInBackground()
> 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
> 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
> 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 	at java.lang.Thread.run(Thread.java:818)
> Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
> 	at android.os.Handler.<init>(Handler.java:200)
> 	at android.os.Handler.<init>(Handler.java:114)
> 	at android.widget.Toast$TN.<init>(Toast.java:345)
> 	at android.widget.Toast.<init>(Toast.java:101)
> 	at android.widget.Toast.makeText(Toast.java:259)
> 	at com.it.legalapps.proviser.CalendarFragment$ApiSimulator.doInBackground(CalendarFragment.java:315)
> 	at com.it.legalapps.proviser.CalendarFragment$ApiSimulator.doInBackground(CalendarFragment.java:291)
> 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 	... 3 more
```

**My code:**

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment_calendar, container, false);

        context = getContext();

        oneDayDecorator = new OneDayDecorator(getActivity());

        tvSelectedDate = (TextView) view.findViewById(R.id.tv_date);

        ButterKnife.bind(view);

        widget = (MaterialCalendarView)view.findViewById(R.id.calendarView);
        widget.setOnDateChangedListener(this);
        widget.setOnMonthChangedListener(this);

        widget.addDecorators(
                new HighlightWeekendsDecorator(),
                oneDayDecorator
        );
        widget.setDateSelected(Calendar.getInstance().getTime(), true);
        tvSelectedDate.setText(FORMATTER.format(getSelectedDates()));
        loadDates();

        // Inflate the layout for this fragment
        return view;
    }

    @Override
    public void onDateSelected(@NonNull MaterialCalendarView widget, @Nullable CalendarDay date, boolean selected) {
      
        tvSelectedDate.setText(FORMATTER.format(getSelectedDates()));
        showBusiness(getSelectedDates());
    }
    private void loadDates()
    {
        DatabaseHelper mDatabaseHelper = new DatabaseHelper(context, DatabaseHelper.DATABASE_NAME, null, DatabaseHelper.DATABASE_VERSION);
        SQLiteDatabase mSqLiteDatabase = mDatabaseHelper.getWritableDatabase();
        
        Cursor cursor = mSqLiteDatabase.query(DatabaseHelper.DATABASE_MY_BUSINESS_TABLE, new String[]{
                        DatabaseHelper._ID, DatabaseHelper.NAME_NUMBER_COLUMN, DatabaseHelper.NUMBER_COLUMN, DatabaseHelper.COURT_COLUMN, DatabaseHelper.JUDGE_COLUMN,
                        DatabaseHelper.FORMA_COLUMN, DatabaseHelper.INVOLVED_COLUMN, DatabaseHelper.DESCRIPTION_COLUMN, DatabaseHelper.DATETIME_BEGIN_COLUMN,
                        DatabaseHelper.DATETIME_UPDATE_COLUMN, DatabaseHelper.ADDRESS_COLUMN}, null,
                null,
                null,
                null,
                DatabaseHelper.DATETIME_BEGIN_COLUMN + " ASC"
        );
        while (cursor.moveToNext()) {

            int id = cursor.getInt(cursor.getColumnIndex(DatabaseHelper._ID));

            numberName = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.NAME_NUMBER_COLUMN));

            number = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.NUMBER_COLUMN));

            court = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.COURT_COLUMN));

            judge = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.JUDGE_COLUMN));

            forma = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.FORMA_COLUMN));

            involved = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.INVOLVED_COLUMN));

            description = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.DESCRIPTION_COLUMN));

            dateTimeBegin = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.DATETIME_BEGIN_COLUMN));

            dateTimeUpdate = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.DATETIME_UPDATE_COLUMN));

            address = cursor.getString(cursor
                    .getColumnIndex(DatabaseHelper.ADDRESS_COLUMN));

            ModelBusiness business = new ModelBusiness();
            business.setNumberName(numberName);
            business.setNumber(number);
            business.setCourt(court);
            business.setJudge(judge);
            business.setForma(forma);
            business.setInvolved(involved);
            business.setDescription(description);
            business.setDateTimeBegin(dateTimeBegin);
            business.setDateTimeUpdate(dateTimeUpdate);
            business.setAddress(address);

            mList.add(business);

            Log.i("LOG_TAG", "ROW " + id + " HAS NAME " + number);
        }
        cursor.close();

        new ApiSimulator().executeOnExecutor(Executors.newSingleThreadExecutor());
    }

private class ApiSimulator extends AsyncTask<Void, Void, List<CalendarDay>> {

        @Override
        protected List<CalendarDay> doInBackground(@NonNull Void... voids) {
            try {
                Thread.sleep(1000); // 2000
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            ArrayList<CalendarDay> dates = new ArrayList<>();

            for (ModelBusiness business : mList) {
                String dateString = business.getDateTimeBegin();
                DateFormat df = new SimpleDateFormat();
                Calendar calendar = Calendar.getInstance();

                try {
                    calendar.setTime(df.parse(dateString));
                    Log.e("DateTest", df.parse(dateString).toString());
                } catch (ParseException e) {
                    e.printStackTrace();
                    Toast.makeText(getContext(), e.getMessage(), Toast.LENGTH_LONG).show();
                }

                 CalendarDay day = CalendarDay.from(calendar);
                 dates.add(day);
            }
            return dates;
        }
       @Override
        protected void onPostExecute(@NonNull List<CalendarDay> calendarDays) {
            super.onPostExecute(calendarDays);

            /*if (isFinishing()) {
                return;
            }*/

            widget.addDecorator(new EventDecorator(getResources().getColor(R.color.colorDotCalendar), calendarDays));
        }
    }
```

**Comment by darko1002001** [comment]
You are showing a toast in doInBackground, you should only do UI related operations in the UI thread. Your error is because you are doing UI stuff in a background thread.

**Comment by quentin41500** [comment]
Thanks @darko1002001, Closing for now
